spring:
    profiles: openshift
  
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql://mysql:3306/carsdb
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
        
server: 
 port: 8080    